name: Unit Test

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy: 
      matrix: 
        node-version: [14.8.x]
    
    steps: 
      - uses: actions/checkout@v2
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with: 
          node-version: ${{matrix.node-version}}
      - name: npm install
        run: npm install
      - name: tests
        run: npm run coverage
      - name: log example
        run: echo "test=hello >> " ${{tests}} 