name: Unit Test

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy: 
      matrix: 
        node-version: [15.x]
    
    steps: 
      - uses: actions/checkout@v3
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with: 
          node-version: ${{matrix.node-version}}
      - name: install dependencies
        run: npm ci
      - name: tests with coverage
        run: npm run coverage